---
- hosts: zookeepers
  vars:
    zookeeper:
      version: 3.4.9
      md5checksum: 3e8506075212c2d41030d874fcc9dcd2
  become: true
  user: vagrant
  tasks:
    - name: install yum packages
      yum:
        name: "{{item}}"
        state: installed
      with_items:
        - wget
        - java-1.8.0-openjdk

    - name: check zookeeper installed or not
      stat:
        path: /var/zookeeper/myid
      register: zk_file

    - name: download zookeeper
      get_url:
        url: http://archive.apache.org/dist/zookeeper/zookeeper-{{zookeeper.version}}/zookeeper-{{zookeeper.version}}.tar.gz
        dest: /tmp/zookeeper-{{zookeeper.version}}.tar.gz
        checksum:
          md5:{{zookeeper.md5checksum}}
      when: not zk_file.stat.exists

    - name: extract zookeeper tar ball
      shell: tar zxf /tmp/zookeeper-{{zookeeper.version}}.tar.gz
      args:
        chdir: /opt
      when: not zk_file.stat.exists

    - name: create symbolic link
      file:
        src: /opt/zookeeper-{{zookeeper.version}}
        dest: /opt/zookeeper
        state: link
      when: not zk_file.stat.exists

    - name: create data dir for zookeeper 
      file: 
        path: /var/zookeeper 
        state: directory 
        owner: root
      when: not zk_file.stat.exists
          
    - name: create myid file
      shell: echo "1" > /var/zookeeper/myid

    - name: place zoo.cfg file
      copy:
        src: zoo.cfg
        dest: /opt/zookeeper/conf/zoo.cfg
      when: not zk_file.stat.exists

    - name: start zookeeper
      shell: /opt/zookeeper/bin/zkServer.sh start


- hosts: solr_servers
  vars:
    solr:
      version: 6.2.1
      md5checksum: 5a781a109446aa8b6d31ed41b83d1f69
    zookeeper_host: 192.168.110.100
    solr_ports:
      - 8901
      - 8902
  become: true
  user: vagrant
  tasks:
    - name: install yum packages
      yum:
        name: "{{item}}"
        state: installed
      with_items:
        - wget
        - java-1.8.0-openjdk

    - name: check solr installed or not
      stat:
        path: /opt/solr-{{ solr.version }}/LICENSE.txt
      register: solrfile

    - name: download solr
      get_url: 
         url: http://archive.apache.org/dist/lucene/solr/{{solr.version}}/solr-{{solr.version}}.tgz
         dest: /tmp/solr-{{solr.version}}.tgz
         checksum:
           md5:{{solr.md5checksum}}
      when: not solrfile.stat.exists

    - name: extract solr tar ball
      shell: tar xf /tmp/solr-{{solr.version}}.tgz
      args:
        chdir: /tmp
      when: not solrfile.stat.exists

    - name: install solr
      shell: test -x /etc/init.d/solr_node_{{ item }} || /tmp/solr-6.2.1/bin/install_solr_service.sh /tmp/solr-{{solr.version}}.tgz -p {{ item }} -s solr_node_{{ item }}
      with_items: 
        - "{{ solr_ports }}"

    - name: set solr host
      shell: sed -i -e "s/^.*\(SOLR_HOST=\).*/\1\"$(ip a show dev eth1 |egrep "inet\s"|awk 'match($2, /([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})/) {print substr($2,RSTART,RLENGTH)}')\"/" /etc/default/solr_node_{{ item }}.in.sh
      with_items: 
        - "{{ solr_ports }}"

    - name: set zookeeper host
      shell: sed -i -e "s/#\(ZK_HOST=\).*/\1{{zookeeper_host}}:2181/" /etc/default/solr_node_{{ item }}.in.sh
      with_items: 
        - "{{ solr_ports }}"

    - name: restart solr
      shell: service solr_node_{{ item }} restart 
      with_items: 
        - "{{ solr_ports }}"

